package gcodeinfo

import (
	"regexp"
	"strconv"
	"strings"
)

var (
	reGeneratedBy = regexp.MustCompile(`(?i)generated by\s+(\S+)\s+V?([\w.+-]+)\s+on\b`)
	reCuraGen     = regexp.MustCompile(`(?i)Cura_SteamEngine\s+([\w.+-]+)`)

	reTotalLayerNumber = regexp.MustCompile(`(?i)total layer number\s*[:=]\s*(\d+)`)
	reFilamentDensity  = regexp.MustCompile(`(?i)filament_density\s*[:=]\s*([\d.]+)`)
	reFilamentDiameter = regexp.MustCompile(`(?i)filament_diameter\s*[:=]\s*([\d.]+)`)
	reMaxZHeight       = regexp.MustCompile(`(?i)max_z_height\s*[:=]\s*([\d.]+)`)
	reCrealityUUID     = regexp.MustCompile(`(?i)creality_uuid\s*[:=]\s*(\S+)`)
	reGenericUUID      = regexp.MustCompile(`(?i)(?:^|[;\s])uuid\s*[:=]\s*([0-9a-fA-F-]{8,})`)
	reTaskID           = regexp.MustCompile(`(?i)(?:creality_)?task_id\s*[:=]\s*(\S+)`)
	reMulticolorMethod = regexp.MustCompile(`(?i)multicolor_method\s*[:=]\s*(\d+)`)

	reMinX = regexp.MustCompile(`(?i)(?:^|[;\s])MINX\s*[:=]\s*(-?[\d.]+)`)
	reMinY = regexp.MustCompile(`(?i)(?:^|[;\s])MINY\s*[:=]\s*(-?[\d.]+)`)
	reMinZ = regexp.MustCompile(`(?i)(?:^|[;\s])MINZ\s*[:=]\s*(-?[\d.]+)`)
	reMaxX = regexp.MustCompile(`(?i)(?:^|[;\s])MAXX\s*[:=]\s*(-?[\d.]+)`)
	reMaxY = regexp.MustCompile(`(?i)(?:^|[;\s])MAXY\s*[:=]\s*(-?[\d.]+)`)
	reMaxZ = regexp.MustCompile(`(?i)(?:^|[;\s])MAXZ\s*[:=]\s*(-?[\d.]+)`)

	reEstimatedTime  = regexp.MustCompile(`(?i)(?:total\s+)?estimated (?:printing )?time[^=:\n]*[=:]\s*([^\n;]+)`)
	reFilamentUsedMM = regexp.MustCompile(`(?i)filament used\s*\[mm\]\s*[=:]\s*([\d.]+)`)
	reFilamentUsedG  = regexp.MustCompile(`(?i)filament used\s*\[g\]\s*[=:]\s*([\d.]+)`)
	reFilamentCost   = regexp.MustCompile(`(?i)(?:total\s+)?filament cost\s*[=:]\s*([\d.]+)`)
	reLayerHeight    = regexp.MustCompile(`(?i)(?:^|[;\s])layer_height\s*[=:]\s*([\d.]+)`)
	reNozzleTemp     = regexp.MustCompile(`(?i)(?:^|[;\s])nozzle_temperature\s*[=:]\s*([\d.]+)`)
	reHotPlateTemp   = regexp.MustCompile(`(?i)(?:^|[;\s])hot_plate_temp\s*[=:]\s*([\d.]+)`)
	reBedTemp        = regexp.MustCompile(`(?i)(?:^|[;\s])bed_temperature\s*[=:]\s*([\d.]+)`)
	reFirstBedTemp   = regexp.MustCompile(`(?i)(?:^|[;\s])first_layer_bed_temperature\s*[=:]\s*([\d.]+)`)
	reFilamentType   = regexp.MustCompile(`(?i)(?:^|[;\s])filament_type\s*[=:]\s*(\S+)`)
	reFilamentColour = regexp.MustCompile(`(?i)(?:^|[;\s])filament_colou?r\s*[=:]\s*(\S+)`)
	rePrinterModel   = regexp.MustCompile(`(?i)(?:^|[;\s])printer_model\s*[=:]\s*([^\n;]+)`)

	reCuraFlavor    = regexp.MustCompile(`(?i);\s*FLAVOR\s*:`)
	reCuraTime      = regexp.MustCompile(`(?i);\s*TIME\s*:\s*(\d+)`)
	reCuraLayerHt   = regexp.MustCompile(`(?i);\s*Layer height\s*:\s*([\d.]+)`)
	reCuraFilamentM = regexp.MustCompile(`(?i);\s*Filament used\s*:\s*([\d.]+)\s*m\b`)
)

// ParseHeader parses a gcode file's head and tail bytes into a
// yaml-frontmatter-safe GCodeInfo plus a separate slice of decoded
// thumbnail images. Either slice may be nil (a caller that only fetched a
// head range passes a nil tail); both are treated as plain text and scanned
// independently for HEADER_BLOCK/bounds/thumbnails (expected near the top,
// so read from head) and Creality Print's settings dump / estimate
// comments (expected near the bottom, so read from tail, but also checked
// against head for a small file whose entire content fits in one read).
func ParseHeader(head, tail []byte) (*GCodeInfo, []Thumbnail, error) {
	headText := string(head)
	tailText := string(tail)
	all := headText
	if tailText != "" {
		all += "\n" + tailText
	}

	info := &GCodeInfo{Dialect: DialectUnknown}

	dialect, generator, version := detectDialect(all)
	info.Dialect = dialect
	info.Generator = generator
	info.GeneratorVersion = version

	if m := reTotalLayerNumber.FindStringSubmatch(all); m != nil {
		if v, err := strconv.Atoi(m[1]); err == nil {
			info.TotalLayers = &v
		}
	}
	info.FilamentDensity = matchFloat(reFilamentDensity, all)
	info.FilamentDiameter = matchFloat(reFilamentDiameter, all)
	info.MaxZHeight = matchFloat(reMaxZHeight, all)

	if m := reCrealityUUID.FindStringSubmatch(all); m != nil {
		info.CrealityUUID = m[1]
	} else if m := reGenericUUID.FindStringSubmatch(all); m != nil {
		info.CrealityUUID = m[1]
	}
	if m := reTaskID.FindStringSubmatch(all); m != nil {
		info.TaskID = m[1]
	}
	if m := reMulticolorMethod.FindStringSubmatch(all); m != nil {
		if v, err := strconv.Atoi(m[1]); err == nil {
			info.MulticolorMethod = &v
		}
	}

	if b := parseBounds(all); b != nil {
		info.Bounds = b
	}

	if est := parseEstimate(all); est != nil {
		info.Estimate = est
	}

	thumbs, meta, warnings := extractThumbnails(headText)
	info.Thumbnails = meta
	info.Warnings = append(info.Warnings, warnings...)

	if headTruncated(headText) {
		info.HeadTruncated = true
		info.Warnings = append(info.Warnings, "head buffer ended before a HEADER_BLOCK or THUMBNAIL_BLOCK closed; increase the head read size for a complete result")
	}

	return info, thumbs, nil
}

// detectDialect identifies the slicer family from generator lines and
// dialect-specific markers. It never returns an empty Dialect.
func detectDialect(all string) (Dialect, string, string) {
	if m := reGeneratedBy.FindStringSubmatch(all); m != nil {
		name, version := m[1], m[2]
		lower := strings.ToLower(name)
		switch {
		case strings.Contains(lower, "creality"):
			return DialectCrealityPrint, name, version
		case strings.Contains(lower, "orcaslicer"):
			return DialectOrcaSlicer, name, version
		case strings.Contains(lower, "bambustudio"):
			return DialectBambuStudio, name, version
		case strings.Contains(lower, "superslicer"):
			return DialectSuperSlicer, name, version
		case strings.Contains(lower, "prusaslicer") || strings.Contains(lower, "slic3r"):
			return DialectPrusaSlicer, name, version
		default:
			// A recognised "generated by <name> V<version> on <date>" line
			// from an unlisted tool: still useful identity, just not one of
			// this package's known dialects.
			return DialectUnknown, name, version
		}
	}
	if strings.Contains(all, "HEADER_BLOCK_START") || strings.Contains(all, "THUMBNAIL_BLOCK_START") {
		// The block format itself is specific to the Creality Print /
		// OrcaSlicer family even when the generator line could not be
		// matched (a truncated head, or a generator string this package
		// does not recognise by name).
		return DialectCrealityPrint, "", ""
	}
	if reCuraFlavor.MatchString(all) {
		if m := reCuraGen.FindStringSubmatch(all); m != nil {
			return DialectCura, "Cura", m[1]
		}
		return DialectCura, "Cura", ""
	}
	if m := reCuraGen.FindStringSubmatch(all); m != nil {
		return DialectCura, "Cura", m[1]
	}
	return DialectUnknown, "", ""
}

func parseBounds(all string) *Bounds {
	b := &Bounds{
		MinX: matchFloat(reMinX, all),
		MinY: matchFloat(reMinY, all),
		MinZ: matchFloat(reMinZ, all),
		MaxX: matchFloat(reMaxX, all),
		MaxY: matchFloat(reMaxY, all),
		MaxZ: matchFloat(reMaxZ, all),
	}
	if b.MinX == nil && b.MinY == nil && b.MinZ == nil && b.MaxX == nil && b.MaxY == nil && b.MaxZ == nil {
		return nil
	}
	return b
}

// parseEstimate reads the settings/estimate comments regardless of the
// detected Dialect: the "key = value" comment style is shared across the
// whole Creality Print / OrcaSlicer / PrusaSlicer / SuperSlicer family, and
// the Cura-specific colon patterns are tried as a fallback whenever the
// shared style found nothing, so this never needs to branch on dialect.
func parseEstimate(all string) *Estimate {
	est := &Estimate{}
	any := false

	if m := reEstimatedTime.FindStringSubmatch(all); m != nil {
		text := strings.TrimSpace(m[1])
		est.EstimatedTimeText = text
		est.EstimatedTimeSeconds = parseDurationSeconds(text)
		any = true
	} else if m := reCuraTime.FindStringSubmatch(all); m != nil {
		if v, err := strconv.ParseFloat(m[1], 64); err == nil {
			est.EstimatedTimeSeconds = &v
			any = true
		}
	}

	if v := matchFloat(reFilamentUsedMM, all); v != nil {
		est.FilamentUsedMM = v
		any = true
	} else if m := reCuraFilamentM.FindStringSubmatch(all); m != nil {
		if v, err := strconv.ParseFloat(m[1], 64); err == nil {
			mm := v * 1000
			est.FilamentUsedMM = &mm
			any = true
		}
	}
	if v := matchFloat(reFilamentUsedG, all); v != nil {
		est.FilamentUsedG = v
		any = true
	}
	if v := matchFloat(reFilamentCost, all); v != nil {
		est.FilamentCost = v
		any = true
	}

	if v := matchFloat(reLayerHeight, all); v != nil {
		est.LayerHeightMM = v
		any = true
	} else if v := matchFloat(reCuraLayerHt, all); v != nil {
		est.LayerHeightMM = v
		any = true
	}

	if v := matchFloat(reNozzleTemp, all); v != nil {
		est.NozzleTemperatureC = v
		any = true
	}

	if v := matchFloat(reHotPlateTemp, all); v != nil {
		est.BedTemperatureC = v
		any = true
	} else if v := matchFloat(reBedTemp, all); v != nil {
		est.BedTemperatureC = v
		any = true
	} else if v := matchFloat(reFirstBedTemp, all); v != nil {
		est.BedTemperatureC = v
		any = true
	}

	if m := reFilamentType.FindStringSubmatch(all); m != nil {
		est.FilamentType = m[1]
		any = true
	}
	if m := reFilamentColour.FindStringSubmatch(all); m != nil {
		est.FilamentColour = m[1]
		any = true
	}
	if m := rePrinterModel.FindStringSubmatch(all); m != nil {
		est.PrinterModel = strings.TrimSpace(m[1])
		any = true
	}

	if !any {
		return nil
	}
	return est
}

func matchFloat(re *regexp.Regexp, text string) *float64 {
	m := re.FindStringSubmatch(text)
	if m == nil {
		return nil
	}
	v, err := strconv.ParseFloat(m[1], 64)
	if err != nil {
		return nil
	}
	return &v
}

// headTruncated reports whether head contains a block start marker with no
// matching end marker, which means the head read was too small to capture
// the whole block.
func headTruncated(head string) bool {
	pairs := [][2]string{
		{"HEADER_BLOCK_START", "HEADER_BLOCK_END"},
	}
	for _, p := range pairs {
		if strings.Count(head, p[0]) > strings.Count(head, p[1]) {
			return true
		}
	}
	if strings.Count(head, "THUMBNAIL_BLOCK_START") > strings.Count(head, "THUMBNAIL_BLOCK_END") {
		return true
	}
	if strings.Count(head, "thumbnail begin") > strings.Count(head, "thumbnail end") {
		return true
	}
	return false
}
