package gcodeinfo

import (
	"encoding/base64"
	"fmt"
	"strings"
	"testing"
)

// buildCrealityHead assembles a realistic Creality Print / OrcaSlicer style
// head, matching the shape confirmed live
// (references/printer-snapshot/extra/light_test_20260928.md, "HTTP Range on
// file download": HEADER_BLOCK with slicer/layer count/max z/uuid, MINX..
// MAXZ bounds, multicolor_method, THUMBNAIL_BLOCK with base64 PNG) and
// byte-for-byte against a captured sample
// (references/K2_Series_Klipper/gcodes/F021/3DBench_PLA_14m.gcode).
func buildCrealityHead(thumbData []byte) string {
	b64 := base64.StdEncoding.EncodeToString(thumbData)
	var b strings.Builder
	b.WriteString("; HEADER_BLOCK_START\n")
	b.WriteString("; generated by Creality_Print V5.1.2.9904 on 2024-08-03 at 17:44:59\n")
	b.WriteString("; total layer number: 192\n")
	b.WriteString("; filament_density: 1.24\n")
	b.WriteString("; filament_diameter: 1.75\n")
	b.WriteString("; max_z_height: 48.00\n")
	b.WriteString("; creality_uuid: 550e8400-e29b-41d4-a716-446655440000\n")
	b.WriteString("; HEADER_BLOCK_END\n\n")
	b.WriteString("; MINX = 145.00\n")
	b.WriteString("; MINY = 159.50\n")
	b.WriteString("; MINZ = 0.00\n")
	b.WriteString("; MAXX = 205.00\n")
	b.WriteString("; MAXY = 190.50\n")
	b.WriteString("; MAXZ = 48.00\n")
	b.WriteString("; multicolor_method = 0\n\n")
	b.WriteString("; THUMBNAIL_BLOCK_START\n")
	b.WriteString(";\n")
	fmt.Fprintf(&b, "; thumbnail begin 32x32 %d\n", len(b64))
	b.WriteString(wrapAsThumbnailComment(b64, 78))
	b.WriteString("; thumbnail end\n")
	b.WriteString("; THUMBNAIL_BLOCK_END\n\n")
	b.WriteString("; EXECUTABLE_BLOCK_START\n")
	b.WriteString("G28\n")
	b.WriteString("M104 S220\n")
	return b.String()
}

// buildCrealityTail assembles the settings/estimate comment block usually
// found at a Creality Print / OrcaSlicer gcode's tail, including the real
// quirk observed in the sample file: two settings comments concatenated
// onto one line with no separating newline.
func buildCrealityTail() string {
	var b strings.Builder
	b.WriteString("; EXECUTABLE_BLOCK_END\n\n")
	b.WriteString("; filament used [mm] = 3643.44\n")
	b.WriteString("; filament used [g] = 10.87\n")
	b.WriteString("; filament cost = 0.22; total filament used [g] = 10.87\n")
	b.WriteString("; total filament cost = 0.22\n")
	b.WriteString("; estimated printing time (normal mode) = 14m 33s\n\n")
	b.WriteString("; CONFIG_BLOCK_START\n")
	b.WriteString("; filament_colour = #00FF00\n")
	b.WriteString("; filament_type = PLA\n")
	b.WriteString("; layer_height = 0.25\n")
	b.WriteString("; max_layer_height = 0.32\n")
	b.WriteString("; nozzle_temperature = 220\n")
	b.WriteString("; nozzle_temperature_initial_layer = 220\n")
	b.WriteString("; hot_plate_temp = 50\n")
	b.WriteString("; hot_plate_temp_initial_layer = 50\n")
	b.WriteString("; printer_model = K2 Plus\n")
	b.WriteString("; CONFIG_BLOCK_END\n")
	return b.String()
}

func TestParseHeader_CrealityPrint(t *testing.T) {
	png := makeTestPNG(t, 32, 32)
	head := []byte(buildCrealityHead(png))
	tail := []byte(buildCrealityTail())

	info, thumbs, err := ParseHeader(head, tail)
	if err != nil {
		t.Fatalf("ParseHeader: %v", err)
	}

	if info.Dialect != DialectCrealityPrint {
		t.Errorf("Dialect = %q, want %q", info.Dialect, DialectCrealityPrint)
	}
	if info.Generator != "Creality_Print" || info.GeneratorVersion != "5.1.2.9904" {
		t.Errorf("Generator = %q %q, want Creality_Print 5.1.2.9904", info.Generator, info.GeneratorVersion)
	}
	if info.TotalLayers == nil || *info.TotalLayers != 192 {
		t.Errorf("TotalLayers = %v, want 192", info.TotalLayers)
	}
	if info.FilamentDensity == nil || *info.FilamentDensity != 1.24 {
		t.Errorf("FilamentDensity = %v, want 1.24", info.FilamentDensity)
	}
	if info.FilamentDiameter == nil || *info.FilamentDiameter != 1.75 {
		t.Errorf("FilamentDiameter = %v, want 1.75", info.FilamentDiameter)
	}
	if info.MaxZHeight == nil || *info.MaxZHeight != 48.00 {
		t.Errorf("MaxZHeight = %v, want 48.00", info.MaxZHeight)
	}
	if info.CrealityUUID != "550e8400-e29b-41d4-a716-446655440000" {
		t.Errorf("CrealityUUID = %q", info.CrealityUUID)
	}
	if info.MulticolorMethod == nil || *info.MulticolorMethod != 0 {
		t.Errorf("MulticolorMethod = %v, want 0", info.MulticolorMethod)
	}

	if info.Bounds == nil {
		t.Fatal("Bounds is nil")
	}
	if info.Bounds.MinX == nil || *info.Bounds.MinX != 145.00 {
		t.Errorf("Bounds.MinX = %v, want 145.00", info.Bounds.MinX)
	}
	if info.Bounds.MaxZ == nil || *info.Bounds.MaxZ != 48.00 {
		t.Errorf("Bounds.MaxZ = %v, want 48.00", info.Bounds.MaxZ)
	}

	if info.Estimate == nil {
		t.Fatal("Estimate is nil")
	}
	e := info.Estimate
	if e.EstimatedTimeText != "14m 33s" {
		t.Errorf("EstimatedTimeText = %q, want %q", e.EstimatedTimeText, "14m 33s")
	}
	if e.EstimatedTimeSeconds == nil || *e.EstimatedTimeSeconds != 873 {
		t.Errorf("EstimatedTimeSeconds = %v, want 873", e.EstimatedTimeSeconds)
	}
	if e.FilamentUsedMM == nil || *e.FilamentUsedMM != 3643.44 {
		t.Errorf("FilamentUsedMM = %v, want 3643.44", e.FilamentUsedMM)
	}
	if e.FilamentUsedG == nil || *e.FilamentUsedG != 10.87 {
		t.Errorf("FilamentUsedG = %v, want 10.87", e.FilamentUsedG)
	}
	if e.FilamentCost == nil || *e.FilamentCost != 0.22 {
		t.Errorf("FilamentCost = %v, want 0.22", e.FilamentCost)
	}
	if e.LayerHeightMM == nil || *e.LayerHeightMM != 0.25 {
		t.Errorf("LayerHeightMM = %v, want 0.25 (must not match max_layer_height)", e.LayerHeightMM)
	}
	if e.NozzleTemperatureC == nil || *e.NozzleTemperatureC != 220 {
		t.Errorf("NozzleTemperatureC = %v, want 220", e.NozzleTemperatureC)
	}
	if e.BedTemperatureC == nil || *e.BedTemperatureC != 50 {
		t.Errorf("BedTemperatureC = %v, want 50", e.BedTemperatureC)
	}
	if e.FilamentType != "PLA" {
		t.Errorf("FilamentType = %q, want PLA", e.FilamentType)
	}
	if e.FilamentColour != "#00FF00" {
		t.Errorf("FilamentColour = %q, want #00FF00", e.FilamentColour)
	}
	if e.PrinterModel != "K2 Plus" {
		t.Errorf("PrinterModel = %q, want %q", e.PrinterModel, "K2 Plus")
	}

	if len(thumbs) != 1 {
		t.Fatalf("len(thumbs) = %d, want 1", len(thumbs))
	}
	th := thumbs[0]
	if th.Truncated {
		t.Error("thumbnail unexpectedly marked truncated")
	}
	if th.Width != 32 || th.Height != 32 {
		t.Errorf("thumbnail dims = %dx%d, want 32x32", th.Width, th.Height)
	}
	if th.Mime != "image/png" {
		t.Errorf("thumbnail mime = %q", th.Mime)
	}
	if string(th.Data) != string(png) {
		t.Error("decoded thumbnail bytes do not match the source PNG")
	}
	if len(info.Thumbnails) != 1 || info.Thumbnails[0].Width != 32 {
		t.Errorf("GCodeInfo.Thumbnails = %+v", info.Thumbnails)
	}

	if info.HeadTruncated {
		t.Error("HeadTruncated should be false for a complete head")
	}
	if len(info.Warnings) != 0 {
		t.Errorf("unexpected warnings: %v", info.Warnings)
	}
}

func TestParseHeader_TruncatedThumbnail(t *testing.T) {
	png := makeTestPNG(t, 64, 64)
	fullHead := buildCrealityHead(png)

	// Cut the head partway through the thumbnail's base64 lines, well
	// before "thumbnail end" or "THUMBNAIL_BLOCK_END", simulating a bounded
	// Range/head read landing mid image.
	beginIdx := strings.Index(fullHead, "; thumbnail begin")
	if beginIdx < 0 {
		t.Fatal("test fixture missing thumbnail begin marker")
	}
	lineEnd := strings.Index(fullHead[beginIdx:], "\n")
	if lineEnd < 0 {
		t.Fatal("test fixture's thumbnail begin line has no terminator")
	}
	dataStart := beginIdx + lineEnd + 1
	cutAt := dataStart + 20 // partway into the first base64 data line
	if cutAt > len(fullHead) {
		t.Fatalf("fixture too short to cut at %d (len %d)", cutAt, len(fullHead))
	}
	truncatedHead := fullHead[:cutAt]

	info, thumbs, err := ParseHeader([]byte(truncatedHead), nil)
	if err != nil {
		t.Fatalf("ParseHeader: %v", err)
	}
	if !info.HeadTruncated {
		t.Error("HeadTruncated should be true for a head cut mid-block")
	}
	if len(thumbs) != 1 {
		t.Fatalf("len(thumbs) = %d, want 1 (the incomplete thumbnail should still be reported)", len(thumbs))
	}
	if !thumbs[0].Truncated {
		t.Error("the cut thumbnail should be reported as Truncated, not silently dropped or treated as complete")
	}
	if len(info.Thumbnails) != 1 || !info.Thumbnails[0].Truncated {
		t.Errorf("GCodeInfo.Thumbnails should also flag the truncation: %+v", info.Thumbnails)
	}
}

func TestParseHeader_TruncatedHeaderBlock(t *testing.T) {
	head := "; HEADER_BLOCK_START\n; generated by Creality_Print V5.1.2.9904 on 2024-08-03 at 17:44:59\n; total layer number: 192\n"
	info, _, err := ParseHeader([]byte(head), nil)
	if err != nil {
		t.Fatalf("ParseHeader: %v", err)
	}
	if !info.HeadTruncated {
		t.Error("HeadTruncated should be true when HEADER_BLOCK_START has no matching HEADER_BLOCK_END")
	}
	if info.TotalLayers == nil || *info.TotalLayers != 192 {
		t.Errorf("a truncated header should still report the fields it did capture; TotalLayers = %v", info.TotalLayers)
	}
}

func TestParseHeader_PrusaSlicer(t *testing.T) {
	head := "; generated by PrusaSlicer 2.6.0+win64 on 2023-10-01 at 12:34:56\n\n; MINX:10\n; MINY:10\n; MAXX:200\n; MAXY:200\n"
	tail := "; filament_type = PLA\n; layer_height = 0.2\n; estimated printing time (normal mode) = 1h 2m 3s\n"
	info, _, err := ParseHeader([]byte(head), []byte(tail))
	if err != nil {
		t.Fatalf("ParseHeader: %v", err)
	}
	if info.Dialect != DialectPrusaSlicer {
		t.Errorf("Dialect = %q, want %q", info.Dialect, DialectPrusaSlicer)
	}
	if info.Generator != "PrusaSlicer" || info.GeneratorVersion != "2.6.0+win64" {
		t.Errorf("Generator = %q %q", info.Generator, info.GeneratorVersion)
	}
	if info.Bounds == nil || info.Bounds.MinX == nil || *info.Bounds.MinX != 10 {
		t.Errorf("Bounds not parsed from colon-style MINX: %+v", info.Bounds)
	}
	if info.Estimate == nil || info.Estimate.FilamentType != "PLA" {
		t.Errorf("Estimate not parsed: %+v", info.Estimate)
	}
	wantSeconds := float64(1*3600 + 2*60 + 3)
	if info.Estimate.EstimatedTimeSeconds == nil || *info.Estimate.EstimatedTimeSeconds != wantSeconds {
		t.Errorf("EstimatedTimeSeconds = %v, want %v", info.Estimate.EstimatedTimeSeconds, wantSeconds)
	}
}

func TestParseHeader_SuperSlicer(t *testing.T) {
	head := "; generated by SuperSlicer 2.5.59 on 2023-01-01 at 00:00:00\n"
	info, _, err := ParseHeader([]byte(head), nil)
	if err != nil {
		t.Fatalf("ParseHeader: %v", err)
	}
	if info.Dialect != DialectSuperSlicer {
		t.Errorf("Dialect = %q, want %q", info.Dialect, DialectSuperSlicer)
	}
}

func TestParseHeader_Cura(t *testing.T) {
	head := ";FLAVOR:Marlin\n;TIME:1234\n;Layer height: 0.2\n;Generated with Cura_SteamEngine 5.2.1\n"
	info, _, err := ParseHeader([]byte(head), nil)
	if err != nil {
		t.Fatalf("ParseHeader: %v", err)
	}
	if info.Dialect != DialectCura {
		t.Errorf("Dialect = %q, want %q", info.Dialect, DialectCura)
	}
	if info.Generator != "Cura" || info.GeneratorVersion != "5.2.1" {
		t.Errorf("Generator = %q %q, want Cura 5.2.1", info.Generator, info.GeneratorVersion)
	}
	if info.Estimate == nil {
		t.Fatal("Estimate is nil")
	}
	if info.Estimate.EstimatedTimeSeconds == nil || *info.Estimate.EstimatedTimeSeconds != 1234 {
		t.Errorf("EstimatedTimeSeconds = %v, want 1234", info.Estimate.EstimatedTimeSeconds)
	}
	if info.Estimate.LayerHeightMM == nil || *info.Estimate.LayerHeightMM != 0.2 {
		t.Errorf("LayerHeightMM = %v, want 0.2", info.Estimate.LayerHeightMM)
	}
}

func TestParseHeader_UnknownDialect(t *testing.T) {
	head := "; a plain gcode file with no recognisable slicer comments\nG28\nG1 X10 Y10\n"
	info, thumbs, err := ParseHeader([]byte(head), nil)
	if err != nil {
		t.Fatalf("ParseHeader: %v", err)
	}
	if info.Dialect != DialectUnknown {
		t.Errorf("Dialect = %q, want %q (never silently omit)", info.Dialect, DialectUnknown)
	}
	if info.Estimate != nil {
		t.Errorf("Estimate = %+v, want nil for an unrecognised file", info.Estimate)
	}
	if info.Bounds != nil {
		t.Errorf("Bounds = %+v, want nil", info.Bounds)
	}
	if len(thumbs) != 0 {
		t.Errorf("thumbs = %+v, want none", thumbs)
	}
}
