package mcpserver

import (
	"archive/zip"
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/sairaph/creality_k2_mcp/internal/domain"
	"github.com/sairaph/creality_k2_mcp/internal/moonraker"
)

// --- synthetic gcode/3mf builders (this package's own copies; gcodeinfo's
// test-only helpers are unexported to that package) ---

// makeTestPNG renders a tiny solid-colour PNG for use as a synthetic
// thumbnail.
func makeTestPNG(t *testing.T, w, h int) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, w, h))
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			img.Set(x, y, color.RGBA{R: 200, G: 40, B: 40, A: 255})
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		t.Fatalf("encode test png: %v", err)
	}
	return buf.Bytes()
}

// wrapThumbnailComment renders base64-encoded data as gcode comment lines,
// matching the real Creality Print / OrcaSlicer THUMBNAIL_BLOCK layout.
func wrapThumbnailComment(b64 string, width int) string {
	var b strings.Builder
	for len(b64) > 0 {
		n := width
		if n > len(b64) {
			n = len(b64)
		}
		b.WriteString("; ")
		b.WriteString(b64[:n])
		b.WriteString("\n")
		b64 = b64[n:]
	}
	return b.String()
}

// buildTestGCode assembles a realistic Creality Print style gcode head with
// an embedded thumbnail and a known layer count, for get_gcode_file and
// inspect_local_gcode.
func buildTestGCode(thumbData []byte, totalLayers int) string {
	b64 := base64.StdEncoding.EncodeToString(thumbData)
	var b strings.Builder
	b.WriteString("; HEADER_BLOCK_START\n")
	b.WriteString("; generated by Creality_Print V5.1.2.9904 on 2024-08-03 at 17:44:59\n")
	fmt.Fprintf(&b, "; total layer number: %d\n", totalLayers)
	b.WriteString("; HEADER_BLOCK_END\n\n")
	b.WriteString("; THUMBNAIL_BLOCK_START\n")
	b.WriteString(";\n")
	fmt.Fprintf(&b, "; thumbnail begin 32x32 %d\n", len(b64))
	b.WriteString(wrapThumbnailComment(b64, 78))
	b.WriteString("; thumbnail end\n")
	b.WriteString("; THUMBNAIL_BLOCK_END\n\n")
	b.WriteString("G28\nM104 S220\n")
	return b.String()
}

// buildPlainGCode is gcode with no recognisable slicer header at all, for
// the unknown-dialect warning test.
func buildPlainGCode() string {
	return "G28\nG1 X10 Y10 F3000\nM104 S200\nM140 S60\n"
}

// buildTestZip writes entries into a new zip file under t.TempDir() and
// returns its path.
func buildTestZip(t *testing.T, entries map[string][]byte) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "test.3mf")
	f, err := os.Create(p)
	if err != nil {
		t.Fatalf("create zip: %v", err)
	}
	defer f.Close()

	zw := zip.NewWriter(f)
	for name, data := range entries {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatalf("zip create %q: %v", name, err)
		}
		if _, err := w.Write(data); err != nil {
			t.Fatalf("zip write %q: %v", name, err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("zip close: %v", err)
	}
	return p
}

const test3MFModelXML = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model" name="Cube"><mesh/></object>
    <object id="2" type="model" name="Cylinder"><mesh/></object>
  </resources>
  <build>
    <item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/>
    <item objectid="2" transform="1 0 0 0 1 0 0 0 1 0 0 0"/>
  </build>
</model>`

func test3MFProjectSettingsJSON() string {
	return `{
		"printer_model": "Creality K2 Plus",
		"nozzle_diameter": ["0.4"],
		"filament_type": ["PLA"],
		"layer_height": "0.2",
		"nozzle_temperature": ["220"],
		"hot_plate_temp": ["55"],
		"an_internal_settings_key_not_on_the_allowlist": "should only appear with full_settings"
	}`
}

func test3MFEntries(t *testing.T) map[string][]byte {
	return map[string][]byte{
		"3D/3dmodel.model":                 []byte(test3MFModelXML),
		"Metadata/project_settings.config": []byte(test3MFProjectSettingsJSON()),
		"Metadata/plate_1.png":             makeTestPNG(t, 64, 64),
	}
}

// --- read-only fixtures/handlers ---

// metadataHandler serves a fixed FileMetadata for every /server/files/metadata
// request, matching moonraker's own "result"-wrapped envelope for GET.
func metadataHandler(t *testing.T, md moonraker.FileMetadata) http.HandlerFunc {
	t.Helper()
	body, err := json.Marshal(map[string]any{"result": md})
	if err != nil {
		t.Fatalf("marshal metadata fixture: %v", err)
	}
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write(body)
	}
}

// headRangeHandler always answers 200 with content in full, exercising the
// "server ignores Range" fallback path moonraker.Client.HeadRange already
// bounds client-side (internal/moonraker/files_test.go's own
// TestHeadRangeFallsBackWhenServerIgnoresRange covers the client half; this
// fake only needs to be simple).
func headRangeHandler(content []byte) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write(content)
	}
}

// directoryFixtureHandler serves files/disk wrapped in the real
// server/files/directory envelope, built from typed structs (not hand-written
// JSON) so a test's expectations stay exact.
func directoryFixtureHandler(t *testing.T, files []moonraker.FileMetadata, disk moonraker.DiskUsage) http.HandlerFunc {
	t.Helper()
	type dirWire struct {
		Dirs      []moonraker.DirEntry     `json:"dirs"`
		Files     []moonraker.FileMetadata `json:"files"`
		DiskUsage moonraker.DiskUsage      `json:"disk_usage"`
		RootInfo  moonraker.RootInfo       `json:"root_info"`
	}
	body, err := json.Marshal(map[string]any{"result": dirWire{
		Files: files, DiskUsage: disk, RootInfo: moonraker.RootInfo{Name: "gcodes", Permissions: "rw"},
	}})
	if err != nil {
		t.Fatalf("marshal directory fixture: %v", err)
	}
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write(body)
	}
}

// --- fakeFileStore: a small stateful gcodes-root simulation for
// upload_gcode_file/delete_gcode_file, so their settle-poll (which re-lists
// the gcodes root after sending) observes the write it just made instead of
// timing out. All loopback-only (httptest), never touches a real printer.

type fakeFileStore struct {
	mu    sync.Mutex
	files map[string]moonraker.GCodeFile
}

func newFakeFileStore(initial ...moonraker.GCodeFile) *fakeFileStore {
	s := &fakeFileStore{files: map[string]moonraker.GCodeFile{}}
	for _, f := range initial {
		s.files[f.Path] = f
	}
	return s
}

func (s *fakeFileStore) listHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		s.mu.Lock()
		list := make([]moonraker.GCodeFile, 0, len(s.files))
		for _, f := range s.files {
			list = append(list, f)
		}
		s.mu.Unlock()
		data, _ := json.Marshal(map[string]any{"result": list})
		w.Header().Set("Content-Type", "application/json")
		w.Write(data)
	}
}

func (s *fakeFileStore) uploadHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(10 << 20); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		name := "uploaded.gcode"
		if fhs := r.MultipartForm.File["file"]; len(fhs) > 0 {
			name = fhs[0].Filename
		}
		s.mu.Lock()
		s.files[name] = moonraker.GCodeFile{Path: name, Size: 123, Modified: 1.0, Permissions: "rw"}
		s.mu.Unlock()
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprintf(w, `{"item": {"root": "gcodes", "path": %q, "modified": 1.0, "size": 123, "permissions": "rw"}, "print_started": false, "print_queued": false, "action": "create_file"}`, name)
	}
}

// gcodesPathHandler serves DELETE for /server/files/gcodes/<name> against
// the same in-memory store; a GET here is never exercised by the
// upload/delete tests (only by get_gcode_file, which serves its own
// headRangeHandler override instead).
func (s *fakeFileStore) gcodesPathHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			w.WriteHeader(http.StatusOK)
			return
		}
		name := strings.TrimPrefix(r.URL.Path, "/server/files/gcodes/")
		name, _ = url.PathUnescape(name)
		s.mu.Lock()
		_, existed := s.files[name]
		delete(s.files, name)
		s.mu.Unlock()
		if !existed {
			w.WriteHeader(http.StatusBadRequest)
			fmt.Fprintf(w, `{"error": {"code": 400, "message": "Invalid file path: gcodes/%s"}}`, name)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprintf(w, `{"result": {"item": {"root": "gcodes", "path": %q}, "action": "delete_file"}}`, name)
	}
}

// currentPrintFilename is the filename tools_status_test.go's own
// printingOverrides() sets on print_stats (state "printing" and filename
// together): a "currently printing" test needs both, since policy and this
// file's own "printing" marking key off print_stats.filename specifically,
// which is empty in the idle fixture even though virtual_sdcard.cur_print_data
// (and so job.filename in the frontmatter) still names the last job.
const currentPrintFilename = "FigureJoints5mmball.stl_PLA_41m51s.gcode"

// --- list_gcode_files ---

func TestListGCodeFilesHappyPathDiskUsageAndCurrentPrint(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/directory": func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.Write(fixture(t, "moonraker", "server_files_directory_gcodes_extended.json"))
		},
		"/printer/objects/query": objectsQueryOverride(t, printingOverrides()),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "list_gcode_files", nil)
	if res.IsError {
		t.Fatalf("list_gcode_files failed: %v", texts(res))
	}
	text := strings.Join(texts(res), "\n")
	for _, want := range []string{
		"sort_by: modified", "total: 13",
		"disk_total_bytes: 6516404224", "disk_used_bytes: 547340288", "disk_free_bytes: 5952286720",
		"current_print_file: " + currentPrintFilename,
		currentPrintFilename,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("list_gcode_files reply missing %q:\n%s", want, text)
		}
	}
	// The row for the currently-printing file must carry the "yes" marker.
	tableStart := strings.Index(text, "| filename |")
	if tableStart == -1 {
		t.Fatalf("list_gcode_files reply missing its table:\n%s", text)
	}
	for _, line := range strings.Split(text[tableStart:], "\n") {
		if strings.Contains(line, currentPrintFilename) && !strings.Contains(line, "| yes |") {
			t.Fatalf("current print file row not marked printing: %q", line)
		}
	}
}

func TestListGCodeFilesSorting(t *testing.T) {
	files := []moonraker.FileMetadata{
		{Filename: "a.gcode", Size: 100, Modified: 300},
		{Filename: "b.gcode", Size: 300, Modified: 100},
		{Filename: "c.gcode", Size: 200, Modified: 200},
	}
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/directory": directoryFixtureHandler(t, files, moonraker.DiskUsage{Total: 1000, Used: 500, Free: 500}),
	})
	cs := testSession(t, deps)

	cases := []struct {
		sortBy string
		order  []string
	}{
		{"", []string{"a.gcode", "c.gcode", "b.gcode"}}, // default: modified desc
		{"modified", []string{"a.gcode", "c.gcode", "b.gcode"}},
		{"name", []string{"a.gcode", "b.gcode", "c.gcode"}}, // asc
		{"size", []string{"b.gcode", "c.gcode", "a.gcode"}}, // desc
	}
	for _, tc := range cases {
		args := map[string]any{}
		if tc.sortBy != "" {
			args["sort_by"] = tc.sortBy
		}
		res := call(t, cs, "list_gcode_files", args)
		if res.IsError {
			t.Fatalf("sort_by=%q failed: %v", tc.sortBy, texts(res))
		}
		text := strings.Join(texts(res), "\n")
		last := -1
		for _, name := range tc.order {
			idx := strings.Index(text, name)
			if idx == -1 {
				t.Fatalf("sort_by=%q: missing %q in:\n%s", tc.sortBy, name, text)
			}
			if idx < last {
				t.Fatalf("sort_by=%q: %q appeared out of order:\n%s", tc.sortBy, name, text)
			}
			last = idx
		}
	}
}

func TestListGCodeFilesInvalidSortBy(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/directory": directoryFixtureHandler(t, nil, moonraker.DiskUsage{}),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "list_gcode_files", map[string]any{"sort_by": "bogus"})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: invalid_input") {
		t.Fatalf("list_gcode_files invalid sort_by reply = %s", text)
	}
}

func TestListGCodeFilesOutOfRangePage(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/directory": directoryFixtureHandler(t, []moonraker.FileMetadata{{Filename: "a.gcode", Size: 1, Modified: 1}}, moonraker.DiskUsage{}),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "list_gcode_files", map[string]any{"page": 999})
	if res.IsError {
		t.Fatalf("list_gcode_files out-of-range page failed: %v", texts(res))
	}
	text := strings.Join(texts(res), "\n")
	if !strings.Contains(text, "total_pages:") {
		t.Fatalf("list_gcode_files out-of-range reply = %s", text)
	}
}

func TestListGCodeFilesEmpty(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/directory": directoryFixtureHandler(t, nil, moonraker.DiskUsage{}),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "list_gcode_files", nil)
	if res.IsError {
		t.Fatalf("list_gcode_files empty failed: %v", texts(res))
	}
	text := strings.Join(texts(res), "\n")
	if !strings.Contains(text, "No gcode files are on this printer's gcodes root.") {
		t.Fatalf("list_gcode_files empty reply = %s", text)
	}
}

func TestListGCodeFilesNotFoundPrinter(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "list_gcode_files", map[string]any{"printer": "does-not-exist"})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: not_found") {
		t.Fatalf("list_gcode_files not_found reply = %s", text)
	}
}

// --- get_gcode_file ---

func TestGetGCodeFileHappyPathWithThumbnail(t *testing.T) {
	thumb := makeTestPNG(t, 32, 32)
	content := []byte(buildTestGCode(thumb, 42))
	md := moonraker.FileMetadata{Filename: "test.gcode", Size: int64(len(content)), Modified: 1000, Slicer: "Unknown"}

	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/metadata": metadataHandler(t, md),
		"/server/files/gcodes/":  headRangeHandler(content),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "get_gcode_file", map[string]any{"filename": "test.gcode"})
	if res.IsError {
		t.Fatalf("get_gcode_file failed: %v", texts(res))
	}
	if n := images(res); n != 1 {
		t.Fatalf("get_gcode_file returned %d image content items, want 1", n)
	}
	text := strings.Join(texts(res), "\n")
	for _, want := range []string{
		"filename: test.gcode", "dialect: creality_print", "total_layers: 42",
		fmt.Sprintf("size_bytes: %d", len(content)),
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("get_gcode_file reply missing %q:\n%s", want, text)
		}
	}
}

func TestGetGCodeFileUnknownDialectWarning(t *testing.T) {
	content := []byte(buildPlainGCode())
	md := moonraker.FileMetadata{Filename: "plain.gcode", Size: int64(len(content)), Modified: 1000}
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/metadata": metadataHandler(t, md),
		"/server/files/gcodes/":  headRangeHandler(content),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "get_gcode_file", map[string]any{"filename": "plain.gcode"})
	if res.IsError {
		t.Fatalf("get_gcode_file failed: %v", texts(res))
	}
	if n := images(res); n != 0 {
		t.Fatalf("get_gcode_file returned %d images for a file with no thumbnail, want 0", n)
	}
	text := strings.Join(texts(res), "\n")
	for _, want := range []string{"dialect: unknown", "slicer dialect could not be recognised"} {
		if !strings.Contains(text, want) {
			t.Fatalf("get_gcode_file unknown-dialect reply missing %q:\n%s", want, text)
		}
	}
}

// buildLargeTestGCodeWithTailEstimate builds a synthetic gcode file whose
// header (thumbnail, total layer count) sits in the first few hundred
// bytes, padded well past the 1 MiB head cap with filler comment lines, and
// whose estimated-printing-time comment is appended only at the very end -
// inside the last 256 KiB tail window, but past the 1 MiB head cap - so
// get_gcode_file can only see it by actually reading the file's tail.
func buildLargeTestGCodeWithTailEstimate(thumb []byte, totalLayers int) string {
	var b strings.Builder
	b.WriteString(buildTestGCode(thumb, totalLayers))
	const filler = "; padding line to grow this synthetic file past the head cap\n"
	for b.Len() < (1<<20)+300_000 {
		b.WriteString(filler)
	}
	b.WriteString("; estimated printing time (normal mode) = 14m 33s\n")
	return b.String()
}

func TestGetGCodeFileReadsTailForEstimateBlockOnLargeFile(t *testing.T) {
	thumb := makeTestPNG(t, 16, 16)
	content := []byte(buildLargeTestGCodeWithTailEstimate(thumb, 10))
	md := moonraker.FileMetadata{Filename: "big.gcode", Size: int64(len(content)), Modified: 1000}
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/metadata": metadataHandler(t, md),
		"/server/files/gcodes/":  headRangeHandler(content),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "get_gcode_file", map[string]any{"filename": "big.gcode"})
	if res.IsError {
		t.Fatalf("get_gcode_file failed: %v", texts(res))
	}
	text := strings.Join(texts(res), "\n")
	for _, want := range []string{"total_layers: 10", "estimated_time_text:", "14m 33s"} {
		if !strings.Contains(text, want) {
			t.Fatalf("get_gcode_file reply missing %q (tail estimate block, only present past the head cap, was not read):\n%s", want, text)
		}
	}
	if strings.Contains(text, "footer/estimate comments") {
		t.Fatalf("get_gcode_file should not warn about missing tail data once the tail was actually read:\n%s", text)
	}
}

func TestGetGCodeFileMarksCurrentlyPrinting(t *testing.T) {
	thumb := makeTestPNG(t, 16, 16)
	content := []byte(buildTestGCode(thumb, 5))
	md := moonraker.FileMetadata{Filename: currentPrintFilename, Size: int64(len(content)), Modified: 1000}
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/metadata": metadataHandler(t, md),
		"/server/files/gcodes/":  headRangeHandler(content),
		"/printer/objects/query": objectsQueryOverride(t, printingOverrides()),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "get_gcode_file", map[string]any{"filename": currentPrintFilename})
	if res.IsError {
		t.Fatalf("get_gcode_file failed: %v", texts(res))
	}
	text := strings.Join(texts(res), "\n")
	if !strings.Contains(text, "printing: true") {
		t.Fatalf("get_gcode_file reply missing printing: true for the current print file:\n%s", text)
	}
}

func TestGetGCodeFileEmptyFilename(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "get_gcode_file", map[string]any{"filename": ""})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: invalid_input") {
		t.Fatalf("get_gcode_file empty filename reply = %s", text)
	}
}

func TestGetGCodeFileMetadataNotFound(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, map[string]http.HandlerFunc{
		"/server/files/metadata": func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusBadRequest)
			w.Write([]byte(`{"error": {"code": 400, "message": "Invalid file path: gcodes/missing.gcode"}}`))
		},
	})
	cs := testSession(t, deps)
	res := call(t, cs, "get_gcode_file", map[string]any{"filename": "missing.gcode"})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: not_found") {
		t.Fatalf("get_gcode_file missing-file reply = %s", text)
	}
}

func TestGetGCodeFileNotFoundPrinter(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "get_gcode_file", map[string]any{"filename": "x.gcode", "printer": "does-not-exist"})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: not_found") {
		t.Fatalf("get_gcode_file not_found printer reply = %s", text)
	}
}

// --- inspect_local_gcode ---

func TestInspectLocalGCodeHappyPathWithThumbnail(t *testing.T) {
	thumb := makeTestPNG(t, 32, 32)
	content := buildTestGCode(thumb, 99)
	dir := t.TempDir()
	p := filepath.Join(dir, "local.gcode")
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatalf("write local gcode: %v", err)
	}

	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "inspect_local_gcode", map[string]any{"path": p})
	if res.IsError {
		t.Fatalf("inspect_local_gcode failed: %v", texts(res))
	}
	if n := images(res); n != 1 {
		t.Fatalf("inspect_local_gcode returned %d images, want 1", n)
	}
	text := strings.Join(texts(res), "\n")
	for _, want := range []string{"dialect: creality_print", "total_layers: 99", fmt.Sprintf("size_bytes: %d", len(content))} {
		if !strings.Contains(text, want) {
			t.Fatalf("inspect_local_gcode reply missing %q:\n%s", want, text)
		}
	}
}

func TestInspectLocalGCodePathNotFound(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "inspect_local_gcode", map[string]any{"path": filepath.Join(t.TempDir(), "does-not-exist.gcode")})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: not_found") {
		t.Fatalf("inspect_local_gcode missing-path reply = %s", text)
	}
}

func TestInspectLocalGCodePathIsDirectory(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "inspect_local_gcode", map[string]any{"path": t.TempDir()})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: invalid_input") {
		t.Fatalf("inspect_local_gcode directory-path reply = %s", text)
	}
}

// resolveLocalFile refuses a symlink outright, the same posture as
// daemon.VerifyDir (dev_docs/review-backlog.md item 59): a symlink pointing
// at an otherwise-valid gcode file must still be rejected before it is ever
// opened.
func TestInspectLocalGCodePathIsSymlink(t *testing.T) {
	dir := t.TempDir()
	real := filepath.Join(dir, "real.gcode")
	if err := os.WriteFile(real, []byte("; test\n"), 0o644); err != nil {
		t.Fatalf("write real gcode: %v", err)
	}
	link := filepath.Join(dir, "link.gcode")
	if err := os.Symlink(real, link); err != nil {
		t.Skipf("symlink not supported in this environment: %v", err)
	}

	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "inspect_local_gcode", map[string]any{"path": link})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: invalid_input") || !strings.Contains(text, "symlink") {
		t.Fatalf("inspect_local_gcode symlink-path reply = %s", text)
	}
}

func TestInspectLocalGCodeEmptyPath(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "inspect_local_gcode", map[string]any{"path": ""})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: invalid_input") {
		t.Fatalf("inspect_local_gcode empty-path reply = %s", text)
	}
}

// --- inspect_local_3mf ---

func TestInspectLocal3MFFilteredSettingsByDefault(t *testing.T) {
	p := buildTestZip(t, test3MFEntries(t))
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "inspect_local_3mf", map[string]any{"path": p})
	if res.IsError {
		t.Fatalf("inspect_local_3mf failed: %v", texts(res))
	}
	if n := images(res); n != 1 {
		t.Fatalf("inspect_local_3mf returned %d images, want 1 (plate_1 thumbnail)", n)
	}
	text := strings.Join(texts(res), "\n")
	for _, want := range []string{
		"dialect: creality_print", "printer_model: Creality K2 Plus", "is_k2_project: true", "settings_count: 7",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("inspect_local_3mf filtered reply missing %q:\n%s", want, text)
		}
	}
	if strings.Contains(text, "an_internal_settings_key_not_on_the_allowlist") {
		t.Fatalf("inspect_local_3mf default (filtered) reply should not include the non-allowlisted key:\n%s", text)
	}
}

func TestInspectLocal3MFFullSettings(t *testing.T) {
	p := buildTestZip(t, test3MFEntries(t))
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "inspect_local_3mf", map[string]any{"path": p, "full_settings": true})
	if res.IsError {
		t.Fatalf("inspect_local_3mf full_settings failed: %v", texts(res))
	}
	text := strings.Join(texts(res), "\n")
	if !strings.Contains(text, "settings_full: true") {
		t.Fatalf("inspect_local_3mf full_settings reply missing settings_full: true:\n%s", text)
	}
	if !strings.Contains(text, "an_internal_settings_key_not_on_the_allowlist") {
		t.Fatalf("inspect_local_3mf full_settings reply should include the non-allowlisted key:\n%s", text)
	}
}

func TestInspectLocal3MFPathNotFound(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "inspect_local_3mf", map[string]any{"path": filepath.Join(t.TempDir(), "missing.3mf")})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: not_found") {
		t.Fatalf("inspect_local_3mf missing-path reply = %s", text)
	}
}

func TestInspectLocal3MFNotAZip(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "not-a-zip.3mf")
	if err := os.WriteFile(p, []byte("this is not a zip file"), 0o644); err != nil {
		t.Fatalf("write bogus 3mf: %v", err)
	}
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "inspect_local_3mf", map[string]any{"path": p})
	if !res.IsError {
		t.Fatalf("inspect_local_3mf accepted a non-zip file: %v", texts(res))
	}
}

// --- upload_gcode_file ---

func writeTempGCode(t *testing.T, name, content string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatalf("write temp gcode %s: %v", name, err)
	}
	return p
}

func TestUploadGCodeFileNewFileSendsImmediately(t *testing.T) {
	store := newFakeFileStore() // empty: target filename does not exist yet
	deps, _ := singlePrinterDeps(t, domain.PresetControl, map[string]http.HandlerFunc{
		"/server/files/list":   store.listHandler(),
		"/server/files/upload": store.uploadHandler(),
	})
	cs := testSession(t, deps)
	local := writeTempGCode(t, "new.gcode", "G28\n")

	res := call(t, cs, "upload_gcode_file", map[string]any{"path": local, "filename": "new.gcode"})
	if res.IsError {
		t.Fatalf("upload_gcode_file failed: %v", texts(res))
	}
	text := strings.Join(texts(res), "\n")
	for _, want := range []string{"accepted: true", "effect: confirmed", "never starts a print"} {
		if !strings.Contains(text, want) {
			t.Fatalf("upload_gcode_file new-file reply missing %q:\n%s", want, text)
		}
	}
	if strings.Contains(text, "proposed: true") {
		t.Fatalf("upload_gcode_file to a new filename should never propose (no confirm_token needed):\n%s", text)
	}
}

func TestUploadGCodeFileOverwriteRequiresToken(t *testing.T) {
	store := newFakeFileStore(moonraker.GCodeFile{Path: "existing.gcode", Size: 10, Modified: 1})
	deps, _ := singlePrinterDeps(t, domain.PresetControl, map[string]http.HandlerFunc{
		"/server/files/list":   store.listHandler(),
		"/server/files/upload": store.uploadHandler(),
	})
	cs := testSession(t, deps)
	local := writeTempGCode(t, "existing.gcode", "G28\n")
	args := map[string]any{"path": local, "filename": "existing.gcode"}

	proposal := call(t, cs, "upload_gcode_file", args)
	if proposal.IsError {
		t.Fatalf("upload_gcode_file proposal failed: %v", texts(proposal))
	}
	ptext := strings.Join(texts(proposal), "\n")
	if !strings.Contains(ptext, "proposed: true") || !strings.Contains(ptext, "Proposal for upload_gcode_file") {
		t.Fatalf("upload_gcode_file overwrite should propose first:\n%s", ptext)
	}
	token := extractYAMLField(t, ptext, "confirm_token")

	args["confirm_token"] = token
	confirmed := call(t, cs, "upload_gcode_file", args)
	if confirmed.IsError {
		t.Fatalf("upload_gcode_file confirmed overwrite failed: %v", texts(confirmed))
	}
	ctext := strings.Join(texts(confirmed), "\n")
	if !strings.Contains(ctext, "accepted: true") {
		t.Fatalf("upload_gcode_file confirmed overwrite reply = %s", ctext)
	}
}

func TestUploadGCodeFileRefusesCurrentPrintFile(t *testing.T) {
	store := newFakeFileStore()
	deps, _ := singlePrinterDeps(t, domain.PresetControl, map[string]http.HandlerFunc{
		"/server/files/list":     store.listHandler(),
		"/server/files/upload":   store.uploadHandler(),
		"/printer/objects/query": objectsQueryOverride(t, printingOverrides()),
	})
	cs := testSession(t, deps)
	local := writeTempGCode(t, "current.gcode", "G28\n")
	res := call(t, cs, "upload_gcode_file", map[string]any{"path": local, "filename": currentPrintFilename})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: conflict") {
		t.Fatalf("upload_gcode_file over current print file reply = %s", text)
	}
}

func TestUploadGCodeFileLocalPathNotFound(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetControl, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "upload_gcode_file", map[string]any{"path": filepath.Join(t.TempDir(), "missing.gcode")})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: not_found") {
		t.Fatalf("upload_gcode_file missing local path reply = %s", text)
	}
}

func TestUploadGCodeFilePresetFiltering(t *testing.T) {
	for _, tc := range []struct {
		preset  domain.ToolPreset
		present bool
	}{
		{domain.PresetMonitor, false},
		{domain.PresetCamera, false},
		{domain.PresetControl, true},
	} {
		deps, _ := singlePrinterDeps(t, tc.preset, nil)
		cs := testSession(t, deps)
		list, err := cs.ListTools(context.Background(), nil)
		if err != nil {
			t.Fatalf("preset %s: ListTools: %v", tc.preset, err)
		}
		present := false
		for _, tool := range list.Tools {
			if tool.Name == "upload_gcode_file" {
				present = true
				if tool.Annotations == nil || tool.Annotations.ReadOnlyHint || tool.Annotations.DestructiveHint == nil || !*tool.Annotations.DestructiveHint {
					t.Fatalf("preset %s: upload_gcode_file annotations = %+v", tc.preset, tool.Annotations)
				}
			}
		}
		if present != tc.present {
			t.Fatalf("preset %s: upload_gcode_file present = %v, want %v", tc.preset, present, tc.present)
		}
	}
}

// TestUploadGCodeFileRejectsInvalidFilenameOverride pins client-side
// validation of upload_gcode_file's filename override: Moonraker enforces
// the same restriction server-side, but this server refuses these outright
// rather than spending a network round trip on a request that can never
// succeed.
func TestUploadGCodeFileRejectsInvalidFilenameOverride(t *testing.T) {
	cases := []struct {
		name     string
		filename string
	}{
		{"forward slash", "sub/dir.gcode"},
		{"backslash", "sub\\dir.gcode"},
		{"parent dir", "../escape.gcode"},
		{"absolute unix path", "/etc/passwd"},
		{"drive letter", "C:\\Windows\\evil.gcode"},
		{"bare colon", "weird:name.gcode"},
		{"control character", "bad\x01name.gcode"},
		{"too long", strings.Repeat("a", 256) + ".gcode"},
		{"leading whitespace", " leading.gcode"},
		{"trailing whitespace", "trailing.gcode "},
		{"fullwidth solidus", "sub／dir.gcode"},
		{"division slash", "sub∕dir.gcode"},
		{"fraction slash", "sub⁄dir.gcode"},
		{"big solidus", "sub⧸dir.gcode"},
		{"fullwidth reverse solidus", "sub＼dir.gcode"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			deps, _ := singlePrinterDeps(t, domain.PresetControl, nil)
			cs := testSession(t, deps)
			local := writeTempGCode(t, "local.gcode", "G28\n")
			res := call(t, cs, "upload_gcode_file", map[string]any{"path": local, "filename": tc.filename})
			text := strings.Join(texts(res), "\n")
			if !res.IsError || !strings.Contains(text, "code: invalid_input") {
				t.Fatalf("upload_gcode_file filename=%q reply = %s", tc.filename, text)
			}
		})
	}
}

// --- delete_gcode_file ---

func TestDeleteGCodeFileProposalThenConfirm(t *testing.T) {
	store := newFakeFileStore(moonraker.GCodeFile{Path: "old.gcode", Size: 10, Modified: 1})
	deps, _ := singlePrinterDeps(t, domain.PresetControl, map[string]http.HandlerFunc{
		"/server/files/list":    store.listHandler(),
		"/server/files/gcodes/": store.gcodesPathHandler(),
	})
	cs := testSession(t, deps)

	proposal := call(t, cs, "delete_gcode_file", map[string]any{"filename": "old.gcode"})
	if proposal.IsError {
		t.Fatalf("delete_gcode_file proposal failed: %v", texts(proposal))
	}
	ptext := strings.Join(texts(proposal), "\n")
	if !strings.Contains(ptext, "proposed: true") || !strings.Contains(ptext, "cannot be undone") {
		t.Fatalf("delete_gcode_file should propose first:\n%s", ptext)
	}
	token := extractYAMLField(t, ptext, "confirm_token")

	confirmed := call(t, cs, "delete_gcode_file", map[string]any{"filename": "old.gcode", "confirm_token": token})
	if confirmed.IsError {
		t.Fatalf("delete_gcode_file confirmed delete failed: %v", texts(confirmed))
	}
	ctext := strings.Join(texts(confirmed), "\n")
	if !strings.Contains(ctext, "accepted: true") || !strings.Contains(ctext, "effect: confirmed") {
		t.Fatalf("delete_gcode_file confirmed reply = %s", ctext)
	}
}

func TestDeleteGCodeFileRefusesCurrentPrintFile(t *testing.T) {
	store := newFakeFileStore(moonraker.GCodeFile{Path: currentPrintFilename, Size: 10, Modified: 1})
	deps, _ := singlePrinterDeps(t, domain.PresetControl, map[string]http.HandlerFunc{
		"/server/files/list":     store.listHandler(),
		"/server/files/gcodes/":  store.gcodesPathHandler(),
		"/printer/objects/query": objectsQueryOverride(t, printingOverrides()),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "delete_gcode_file", map[string]any{"filename": currentPrintFilename})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: conflict") {
		t.Fatalf("delete_gcode_file current print file reply = %s", text)
	}
}

// TestDeleteGCodeFileRefusesCurrentPrintFileWhilePaused pins that "never
// delete the current print file" holds while paused too, not just while
// actively printing: print_stats.filename still names the paused job
// (pausedOverrides), and checkDelete keys only on that filename, with no
// bucket condition of its own.
func TestDeleteGCodeFileRefusesCurrentPrintFileWhilePaused(t *testing.T) {
	store := newFakeFileStore(moonraker.GCodeFile{Path: currentPrintFilename, Size: 10, Modified: 1})
	deps, _ := singlePrinterDeps(t, domain.PresetControl, map[string]http.HandlerFunc{
		"/server/files/list":     store.listHandler(),
		"/server/files/gcodes/":  store.gcodesPathHandler(),
		"/printer/objects/query": objectsQueryOverride(t, pausedOverrides(140)),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "delete_gcode_file", map[string]any{"filename": currentPrintFilename})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: conflict") {
		t.Fatalf("delete_gcode_file current print file while paused reply = %s", text)
	}
}

func TestDeleteGCodeFileUnknownTokenIsNotFound(t *testing.T) {
	store := newFakeFileStore(moonraker.GCodeFile{Path: "old.gcode", Size: 10, Modified: 1})
	deps, _ := singlePrinterDeps(t, domain.PresetControl, map[string]http.HandlerFunc{
		"/server/files/list":    store.listHandler(),
		"/server/files/gcodes/": store.gcodesPathHandler(),
	})
	cs := testSession(t, deps)
	res := call(t, cs, "delete_gcode_file", map[string]any{"filename": "old.gcode", "confirm_token": "not-a-real-token"})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: not_found") {
		t.Fatalf("delete_gcode_file unknown token reply = %s", text)
	}
}

func TestDeleteGCodeFileEmptyFilename(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetControl, nil)
	cs := testSession(t, deps)
	res := call(t, cs, "delete_gcode_file", map[string]any{"filename": ""})
	text := strings.Join(texts(res), "\n")
	if !res.IsError || !strings.Contains(text, "code: invalid_input") {
		t.Fatalf("delete_gcode_file empty filename reply = %s", text)
	}
}

// TestDeleteGCodeFileRejectsInvalidFilename pins the same client-side
// filename validation upload_gcode_file's filename override gets
// (validateRemoteFilename), applied here to delete_gcode_file's target
// filename.
func TestDeleteGCodeFileRejectsInvalidFilename(t *testing.T) {
	cases := []struct {
		name     string
		filename string
	}{
		{"forward slash", "sub/dir.gcode"},
		{"backslash", "sub\\dir.gcode"},
		{"parent dir", "../escape.gcode"},
		{"absolute unix path", "/etc/passwd"},
		{"drive letter", "C:\\Windows\\evil.gcode"},
		{"bare colon", "weird:name.gcode"},
		{"control character", "bad\x01name.gcode"},
		{"too long", strings.Repeat("a", 256) + ".gcode"},
		{"leading whitespace", " leading.gcode"},
		{"trailing whitespace", "trailing.gcode "},
		{"fullwidth solidus", "sub／dir.gcode"},
		{"division slash", "sub∕dir.gcode"},
		{"fraction slash", "sub⁄dir.gcode"},
		{"big solidus", "sub⧸dir.gcode"},
		{"fullwidth reverse solidus", "sub＼dir.gcode"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			deps, _ := singlePrinterDeps(t, domain.PresetControl, nil)
			cs := testSession(t, deps)
			res := call(t, cs, "delete_gcode_file", map[string]any{"filename": tc.filename})
			text := strings.Join(texts(res), "\n")
			if !res.IsError || !strings.Contains(text, "code: invalid_input") {
				t.Fatalf("delete_gcode_file filename=%q reply = %s", tc.filename, text)
			}
		})
	}
}

func TestDeleteGCodeFilePresetFiltering(t *testing.T) {
	deps, _ := singlePrinterDeps(t, domain.PresetMonitor, nil)
	cs := testSession(t, deps)
	list, err := cs.ListTools(context.Background(), nil)
	if err != nil {
		t.Fatal(err)
	}
	for _, tool := range list.Tools {
		if tool.Name == "delete_gcode_file" {
			t.Fatal("delete_gcode_file registered under preset monitor")
		}
	}
}

// extractYAMLField pulls "key: value" from text's first matching line (the
// frontmatter block), trimming any surrounding quotes YAML may have added.
func extractYAMLField(t *testing.T, text, key string) string {
	t.Helper()
	prefix := key + ": "
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, prefix) {
			return strings.Trim(strings.TrimPrefix(line, prefix), `"`)
		}
	}
	t.Fatalf("field %q not found in:\n%s", key, text)
	return ""
}
